name: Run tests

on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["*"]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
            - run: npm install
            - run: npm run test-coverage

            - name: Upload coverage to Coveralls
              uses: coverallsapp/github-action@v1
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                path-to-lcov: coverage/lcov.info